'use strict';
// IISER Aptitude Test 2022 - Complete Question Bank
const questionBank = {
    Biology: [
        {
            id: 1,
            text: "Match the features of a plant cell listed in Column I with their corresponding examples in Column II.",
            image: "biology_q1_columns.jpg",
            options: [
                "i and t; ii and r; iii and s; iv and q",
                "i and u; ii and r; iii and s; iv and p",
                "i and u; ii and r; iii and q; iv and p",
                "i and r; ii and t; iii and s; iv and q"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 2,
            text: "Shown below are some of the reactions that occur in the metabolic pathway leading to complete oxidation of glucose during aerobic respiration. Choose the CORRECT sequence of reactions during the complete oxidation of glucose.",
            image: "biology_q2_reactions.jpg",
            options: [
                "ii; i; iii; iv",
                "i; iii; iv; ii",
                "i; ii; iii; iv",
                "ii; iii; i; iv"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 3,
            text: "In a given species of flowering plant, the colour of the seeds is exclusively determined by the colour of its seed coat. Seed coat colour in this species is governed by a nuclear gene with two alleles. The WHITE (W) allele is dominant over brown (w) allele. If a plant with brown seeds (ww) is crossed as a female with pollen from a white seed (WW) plant, what will be the seed colour and the genotype of the embryo in the resultant seeds obtained from this cross?",
            options: [
                "Brown seeds with Ww embryo",
                "White seeds with Ww embryo",
                "Brown seeds with ww embryo",
                "White seeds with ww embryo"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 4,
            text: "During the CoVID-19 pandemic, SARS-CoV2 virus mutated multiple times giving rise to many variants. What is the genetic material of the SARS-CoV2 virus?",
            options: [
                "Single stranded RNA",
                "Double stranded RNA",
                "Single stranded DNA",
                "Double stranded DNA"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 5,
            text: "Lymph is an important body fluid. Choose the INCORRECT statement about the lymph.",
            options: [
                "It remains as an interstitial fluid and is never put back into circulation.",
                "It is the interstitial fluid generated by the passage of liquid between the cells of the capillary.",
                "It is colourless and has similar mineral composition as of plasma.",
                "Fat digested in the intestine is absorbed through the lymph."
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 6,
            text: "Interneurons play an important role in the execution of spinal cord-mediated reflex action. Where are these interneurons located?",
            options: [
                "Gray matter",
                "White matter",
                "Dorsal root ganglion",
                "Muscle spindle"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 7,
            text: "Osmoreceptors are sensitive to changes in ionic concentrations and volumes of body fluids. Which among the following best describes the function of these osmoreceptors?",
            options: [
                "They stimulate hypothalamus to facilitate the release of the anti-diuretic hormone and increase water reabsorption.",
                "They stimulate pituitary gland to facilitate the secretion of mineralocorticoids to adjust the changes in mineral composition of the body fluid.",
                "They stimulate atrial wall to release atrial natriuretic factor to induce vasodilation and reduce blood pressure.",
                "They stimulate renin production to induce vasoconstriction and increase blood pressure."
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 8,
            text: "A single point mutation in gene 'X' results in breathing difficulty, hypertension as well as partial sterility. Which among the following phenomenon best explains the observed phenotypes?",
            options: [
                "Pleiotropy",
                "Incomplete dominance",
                "Linkage",
                "Partial dominance"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 9,
            text: "In a cross between individuals of the genotypes PpQQRrSS and ppqqRrSS, what will be the expected number of progenies with the genotype ppQQRrSS in a population of 400 individuals, assuming independent assortment?",
            options: [
                "0",
                "100",
                "200",
                "25"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 10,
            text: "Organisms in which of the following phyla are triploblastic, acoelomate and have bilateral symmetry?",
            options: [
                "Platyhelminthes",
                "Mollusca",
                "Arthropoda",
                "Hemichordata"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 11,
            text: "Consider the following biomes: Tropical Rainforest (P); Tundra (Q); Desert (R) and Coastal zone (S). Choose the most probable descending order of Net Primary Productivity of these biomes.",
            options: [
                "P > S > Q > R",
                "P > Q > S > R",
                "Q > P > S > R",
                "R > Q > S > P"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 12,
            text: "Nine percent of a population cannot taste a certain food item because of a recessive allele of the gene IAT. Assuming the population is in Hardy-Weinberg equilibrium, what will be the frequency of dominant and recessive alleles, respectively?",
            options: [
                "0.7 and 0.3",
                "0.9 and 0.1",
                "0.3 and 0.7",
                "0.1 and 0.9"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 13,
            text: "As opposed to DNA replication within the cell, discontinuous synthesis of DNA does NOT occur in a polymerase chain reaction (PCR). Why?",
            options: [
                "Denaturation step in PCR substitutes for the replication fork and Taq polymerase extends DNA only in the 5′ to 3′ direction.",
                "The replication fork is formed and Taq polymerase extends DNA in both 3′ to 5′ and 5′ to 3′ direction.",
                "Denaturation step in PCR substitutes for the replication fork and Taq polymerase extends DNA only in the 3′ to 5′ direction.",
                "The replication fork is formed and DNA ligase activity of the Taq polymerase joins the discontinuous fragments."
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 14,
            text: "Which of the following figures CORRECTLY represents the chemiosmotic hypothesis of ATP synthesis occuring in a mitochondrion in a cell? (Keys for the figure; IMS: Intermembrane space, IMM: Inner mitochondrial membrane, MM: Mitochondrial matrix, ETC: Electron transport chain)",
            image: "biology_q14_diagram.jpg",
            options: [
                "Figure A",
                "Figure B",
                "Figure C",
                "Figure D"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 15,
            text: "Let 'X' be the perpendicular distance from the centromere of each chromosome to the equatorial plane of a human cell. Which of the following stages of the cell cycle is most likely to have the HIGHEST average value of 'X'?",
            options: [
                "Late anaphase",
                "Metaphase",
                "Early anaphase",
                "Early metaphase"
            ],
            correct: 0, // A
            marks: 4
        }
    ],
    
    Chemistry: [
        {
            id: 1,
            text: "The products of the reaction between aqueous solutions of K₄[Fe(CN)₆] and ½H₂O₂ are",
            options: [
                "K₃[Fe(CN)₆] and KOH",
                "K₃[Fe(CN)₆] and H₂O",
                "K₃[Fe(CN)₆], H₂O and O₂",
                "K₄[Fe(CN)₅(OH)] and HCN"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 2,
            text: "For the colourless complex [M(H₂O)₆]ⁿ⁺, where M is a 3d transition metal, the CORRECT ground state d-electron configuration of M is",
            options: [
                "(t₂g)⁶(eg)⁴",
                "(t₂g)³(eg)⁰",
                "(t₂g)⁶(eg)²",
                "(t₂g)⁴(eg)²"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 3,
            text: "Choose the correct statement about the structure of C₆₀ fullerene.",
            options: [
                "5-membered rings are fused with 6-membered rings ONLY.",
                "6-membered rings are fused with 5-membered rings ONLY.",
                "6-membered rings are fused with 6-membered rings ONLY.",
                "5-membered rings are fused with both 5-membered and 6-membered rings."
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 4,
            text: "The first to fifth ionization energies (IE) of two p-block elements X and Y are given below.\n\nElement X: IE₁=6.0 eV, IE₂=18.8 eV, IE₃=28.4 eV, IE₄=120.0 eV, IE₅=153.7 eV\nElement Y: IE₁=8.2 eV, IE₂=16.3 eV, IE₃=33.5 eV, IE₄=45.1 eV, IE₅=166.7 eV\n\nThe number of valence electrons in X and Y respectively are",
            options: [
                "3, 4",
                "4, 5",
                "3, 5",
                "1, 4"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 5,
            text: "Which of the following expressions represents the hydrogen atom wave function ψ(r) shown in the figure? (r is the distance of the electron from the nucleus and a₀ is a constant)",
            image: "chemistry_q5_wavefunction.jpg",
            options: [
                "(1/4√2π)(1/a₀)³ᐟ²(2 - r/a₀)e⁻ʳᐟ²ᵃ⁰",
                "(1/√π)(1/a₀)³ᐟ²e⁻ʳᐟ²ᵃ⁰",
                "(1/√6π)(1/a₀)³ᐟ²(r/a₀)e⁻ʳᐟ²ᵃ⁰",
                "(1/√3π)(1/a₀)³ᐟ²(3 - 2r/a₀ + 2r²/9a₀²)e⁻ʳᐟ³ᵃ⁰"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 6,
            text: "Which of the following molecules are aromatic?",
            image: "chemistry_q6_molecules.jpg",
            options: [
                "M, N and O only",
                "M, N, O, and P",
                "M and O only",
                "N and P only"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 7,
            text: "Which of the following are aryl bromides?",
            image: "chemistry_q7_compounds.jpg",
            options: [
                "N and P only",
                "N, O and P only",
                "M, O and P only",
                "N and O only"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 8,
            text: "Benzamide is treated with Br₂ and NaOH(aq) to form the product X, which is then reacted with NaNO₂ and HCl(aq) at 0-5°C to form Y. Y is immediately treated with ethanol to give Z. What is Z?",
            image: "chemistry_q8_structures.jpg",
            options: [
                "Structure A",
                "Structure B",
                "Structure C",
                "Structure D"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 9,
            text: "In the following reaction sequence, the major products M, N, and O respectively are",
            image: "chemistry_q9_reaction.jpg",
            options: [
                "Option A",
                "Option B",
                "Option C",
                "Option D"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 10,
            text: "The major product P of the following reaction is",
            image: "chemistry_q10_reaction.jpg",
            options: [
                "Product A",
                "Product B",
                "Product C",
                "Product D"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 11,
            text: "An aqueous solution contains 1.0 M of X²⁺ and 0.001 M of Y²⁺ ions at 25°C. X²⁺ and Y²⁺ ions do not interact with each other. This solution is put in an electrolytic cell and the voltage is gradually increased till a current begins to flow through the cell. The voltage is maintained at this point and a deposit is observed on the cathode. What is the composition of the material deposited on the cathode?\n\n(Given: Atomic weight of X is 63 and Y is 200.\nX²⁺ + 2e⁻ → X, E⁰ = 0.35 V\nY²⁺ + 2e⁻ → Y, E⁰ = 0.40 V\nE⁰ is the standard reduction potential.)",
            options: [
                "Only X",
                "24% X and 76% Y by weight",
                "98% X and 2% Y by weight",
                "Only Y"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 12,
            text: "For the reaction involving ideal gases, A(g) + 2B(g) ⇋ 2C(g) + 3D(g), which of the following plots is qualitatively correct? (Kp and Kc are the equilibrium constants in terms of pressure and concentration respectively. T is the absolute temperature.)",
            image: "chemistry_q12_graphs.jpg",
            options: [
                "Graph A",
                "Graph B",
                "Graph C",
                "Graph D"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 13,
            text: "The van der Waals equation for a real gas is given by [P + a/V²](V - b) = RT. What is the dimension of (a/b)?",
            options: [
                "ML²T⁻²",
                "ML⁻¹T⁻²",
                "MLT⁻²",
                "ML²T⁻¹"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 14,
            text: "2 g of naphthoic acid (molecular weight = 172 g mol⁻¹) dissolved in 20 mL of benzene shows a freezing point depression of 2 K. For benzene, the freezing point depression constant, Kf = 5 K kg mol⁻¹ and the density is 0.88 g mL⁻¹. What is the magnitude of the van't Hoff factor?",
            options: [
                "0.605",
                "605.0",
                "0.688",
                "688.0"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 15,
            text: "Identify the correct order of the molecules with respect to the magnitude of their dipole moment:",
            image: "chemistry_q15_molecules.jpg",
            options: [
                "Order A",
                "Order B",
                "Order C",
                "Order D"
            ],
            correct: 1, // B
            marks: 4
        }
    ],
    
    Mathematics: [
        {
            id: 1,
            text: "A randomly chosen card from a deck of 52 cards is given to be a black card (i.e. Spade or Club). What is the probability that it is either a face card (i.e. King, Queen or Jack) or a Spade?",
            options: [
                "8/13",
                "9/13",
                "19/26",
                "7/13"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 2,
            text: "Let ω be a complex root of the quadratic polynomial x² + x + 1. The value of (ω + 1/ω)·(ω² + 1/ω²)···(ω¹⁰⁰ + 1/ω¹⁰⁰) is",
            options: [
                "-2³³",
                "-2³¹",
                "2³³",
                "2³¹"
            ],
            correct: 3, // D
            marks: 4
        },
        {
            id: 3,
            text: "Let f(x) = aₙxⁿ + aₙ₋₁xⁿ⁻¹ + ··· + a₁x + a₀ be a polynomial. Suppose that f(0) = 0, df/dx|ₓ₌₀ = 1, d²f/dx²|ₓ₌₀ = 4 and d³f/dx³ = d⁵f/dx⁵. Then f(5) =",
            options: [
                "55",
                "25",
                "35",
                "105"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 4,
            text: "Let S be the set of all unit vectors in the XY-plane. Then the set S has",
            options: [
                "Infinitely many elements",
                "2 elements",
                "4 elements",
                "8 elements"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 5,
            text: "A lab reports that the global average temperature in the year 2020 was 14.9°C and predicts that the global average temperature will increase at the rate of 1% per year. What will be the global average temperature in the year 2035?",
            options: [
                "17.298°C",
                "15.049°C",
                "17.135°C",
                "17.471°C"
            ],
            correct: 3, // D
            marks: 4
        },
        {
            id: 6,
            text: "Let X be the set of all 2×2 matrices with real entries and R ⊂ X×X be the relation R = {(A,B) : AB = BA}. Which of the following statements is true?",
            options: [
                "R is reflexive and symmetric but not transitive",
                "R is reflexive and transitive but not symmetric",
                "R is symmetric and transitive but not reflexive",
                "R is an equivalance relation"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 7,
            text: "For a natural number n, let Cₙ be the curve in the XY-plane given by y = xⁿ, where 0 ≤ x ≤ 1. Let Aₙ denote the area of the region bounded between Cₙ and Cₙ₊₁. Then the largest value of Aₙ is",
            options: [
                "1/6",
                "1/2",
                "1/3",
                "1/12"
            ],
            correct: 3, // D
            marks: 4
        },
        {
            id: 8,
            text: "Let f be a continuous function on [0,1] and F be its antiderivative. If F(0) = 1 and ∫₀¹ f(x)dx = 1, then F(1) is",
            options: [
                "2",
                "0",
                "1",
                "1/2"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 9,
            text: "Let a be a nonzero real number and f : ℝ → ℝ be a continuous function such that f′(x) > 0 for all x ∈ ℝ. Consider g(x) = f(2a²x - ax²). Then g has",
            options: [
                "Local maxima at x = a if a > 0",
                "Local maxima at x = a if a < 0",
                "Local minima at x = a if a > 0",
                "A point of inflection at x = a"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 10,
            text: "Let A be the matrix [cos θ, 0, -sin θ; 1, 1, 1; sin θ, 0, cos θ]. For any natural number k, the determinant of Aᵏ is",
            options: [
                "1",
                "-1",
                "(-1)ᵏ",
                "0"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 11,
            text: "Consider the vectors: a⃗ = î + xĵ + 2k̂, b⃗ = î + 2ĵ + xk̂, c⃗ = 2î + ĵ + 3k̂. The values of x for which there is at least one nonzero vector perpendicular to the vectors a⃗, b⃗ and c⃗ are",
            options: [
                "0, 2",
                "-2, 2",
                "7/2, 0",
                "4, -2"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 12,
            text: "Consider the tangent lines to the circle x² + y² = 1 at points P = (1,0) and Q = (1/√2, 1/√2). If R is the point of intersection of these two tangent lines, then ∠PRQ is:",
            options: [
                "3π/4",
                "π/4",
                "5π/6",
                "π/6"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 13,
            text: "The function given by f(x) = 2x³ - 15x² + 36x - 5 is",
            options: [
                "Increasing on the interval (0, 2)",
                "Decreasing on the interval (-3, 0)",
                "Increasing on the interval (2, 3)",
                "Decreasing on the interval (3, ∞)"
            ],
            correct: 3, // D
            marks: 4
        },
        {
            id: 14,
            text: "The value of the integral ∫₁¹⁰⁰ [x]/x dx, where [x] is the greatest integer less than or equal to x for any real number x, is",
            options: [
                "log(100⁹⁹/99!)",
                "log(100⁹⁹/98!)",
                "log(100⁹⁸/99!)",
                "log(100⁹⁸/98!)"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 15,
            text: "For arbitrary constants α, β, the differential equation representing the family of curves y = (αx + β)eˣ is",
            options: [
                "y″ - 2y′ + y = 0",
                "y″ - y′ + y = 0",
                "y″ - 2y′ - y = 0",
                "y″ - y′ - y = 0"
            ],
            correct: 0, // A
            marks: 4
        }
    ],
    
    Physics: [
        {
            id: 1,
            text: "A particle experiences an acceleration a⃗ = αv⃗, where v⃗ is the velocity of the particle and α is a constant. If the distances traveled by the particle in the time intervals t₂ - t₁ and t₃ - t₁ are S₁₂ and S₁₃, respectively, which of the following relations is true?",
            options: [
                "S₁₃/S₁₂ = [exp[α(t₃-t₁)] - 1] / [exp[α(t₂-t₁)] - 1]",
                "S₁₃/S₁₂ = exp[α(t₃-t₁)] / exp[α(t₂-t₁)]",
                "S₁₃/S₁₂ = log[α(t₃-t₁)] / log[α(t₂-t₁)]",
                "S₁₃/S₁₂ = [log[α(t₃-t₁)] - 1] / [log[α(t₂-t₁)] - 1]"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 2,
            text: "A point mass m attached to a massless string is undergoing circular motion in a vertical plane. The length of the string is R and the acceleration due to gravity is g. If the minimum value of the tension in the string is 2mg, the maximum speed of this circular motion of the point mass is",
            options: [
                "√(7gR)",
                "√(7gR/2)",
                "√(6gR)",
                "4√(gR)"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 3,
            text: "An object is released from rest from the inner edge of a hemispherical bowl, and it falls under gravity. The coefficient of kinetic friction between the object and the bowl is μ. If the object covers an angular displacement θ with respect to the center of the hemisphere when it stops for the first time, which of the following expressions is correct?",
            image: "physics_q3_hemisphere.jpg",
            options: [
                "μ = cot(θ/2)",
                "μ = cot(θ)",
                "μ = tan(θ)",
                "μ = tan(θ/2)"
            ],
            correct: 3, // D
            marks: 4
        },
        {
            id: 4,
            text: "As shown in the figure a block is resting on a frictionless floor and is attached to the free end of a spring. The right edge of the block in equilibrium is at a distance d from the wall. When the spring is compressed by a distance d/2 and released, the time-period of the motion is T. Similarly, when compressed by a distance 2d and released, the time-period is T′. Considering elastic collision between the block and the wall, what is the value of the quantity T′/T?",
            image: "physics_q4_spring.jpg",
            options: [
                "2/3",
                "1",
                "3/4",
                "1/4"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 5,
            text: "A liquid of density ρ in a container weighs W. A cubic block of side L and density ρb < ρ is pushed by a stick to completely submerge the block in the liquid without touching the bottom. If g is the acceleration due to the gravity and liquid displaced by the stick is negligible, what is the new weight of the container as registered by the weighing machine below?",
            options: [
                "W + ρgL³",
                "W + ρbgL³",
                "W + (ρ - ρb)gL³",
                "W + (ρb - ρ)gL³"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 6,
            text: "A monoatomic ideal gas at pressure P and volume V is first adiabatically compressed to volume V/8 and then is allowed to expand isothermally back to its original volume. What is the final pressure of the gas?",
            options: [
                "4P",
                "2P",
                "P",
                "P/2"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 7,
            text: "A particle of mass m is released from rest at a height h above the ground. It falls freely under gravity and hits a massless platform placed on a spring of spring constant k. The platform and the particle move together and compress the spring by a maximum distance x. What is the value of x?",
            options: [
                "x = (mg + √(m²g² + 2kmgh))/k",
                "x = (mg - √(m²g² + 2kmgh))/k",
                "x = (2mg + √(4m²g² + 8kmgh))/2k",
                "x = (mg + √(m²g² + 4kmgh))/k"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 8,
            text: "A solid sphere of radius R and mass M is rolling without slipping on a horizontal surface with speed v. It then rolls up an inclined plane of angle θ. The maximum distance traveled along the incline before it stops is",
            options: [
                "7v²/(10g sin θ)",
                "v²/(2g sin θ)",
                "5v²/(7g sin θ)",
                "3v²/(5g sin θ)"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 9,
            text: "Two identical spheres of radius R and mass M are placed such that their centers are separated by a distance 4R. A small mass m is placed at the midpoint between the centers of the two spheres. If the small mass is displaced slightly along the line joining the centers, the frequency of its oscillation is",
            options: [
                "f = (1/2π)√(GM/4R³)",
                "f = (1/π)√(GM/4R³)",
                "f = (1/2π)√(2GM/R³)",
                "f = (1/2π)√(GM/2R³)"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 10,
            text: "A parallel plate capacitor with plate area A and separation d is filled with a dielectric of dielectric constant K. The capacitor is connected to a battery of voltage V. The battery is then disconnected and the dielectric slab is removed. What is the change in energy stored in the capacitor?",
            options: [
                "ε₀AV²(K-1)/(2d)",
                "ε₀AV²(K+1)/(2d)",
                "ε₀AV²K(K-1)/(2d)",
                "ε₀AV²(K²-1)/(2Kd)"
            ],
            correct: 3, // D
            marks: 4
        },
        {
            id: 11,
            text: "A conducting rod of length L is rotated about one of its ends with constant angular velocity ω in a uniform magnetic field B perpendicular to the plane of rotation. The emf induced between the ends of the rod is",
            options: [
                "BωL²/4",
                "BωL²/2",
                "BωL²",
                "2BωL²"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 12,
            text: "In an AC circuit, a resistor R, inductor L, and capacitor C are connected in series. The circuit is connected to an AC source of voltage V and angular frequency ω. At resonance, which statement is correct?",
            options: [
                "The impedance is minimum and equals R",
                "The current leads the voltage",
                "The power factor is zero",
                "The voltage across L and C are in phase"
            ],
            correct: 0, // A
            marks: 4
        },
        {
            id: 13,
            text: "Light of wavelength λ falls on a metal surface with work function φ. The maximum kinetic energy of the photoelectrons is K. If the wavelength is changed to λ/2, the maximum kinetic energy becomes K'. What is K'?",
            options: [
                "2K + hc/λ",
                "2K - hc/λ",
                "K + hc/λ",
                "K + 2hc/λ"
            ],
            correct: 2, // C
            marks: 4
        },
        {
            id: 14,
            text: "An electron in a hydrogen atom makes a transition from n = 4 to n = 2. The wavelength of the photon emitted is",
            options: [
                "486 nm",
                "656 nm",
                "434 nm",
                "410 nm"
            ],
            correct: 1, // B
            marks: 4
        },
        {
            id: 15,
            text: "The binding energy per nucleon for a nucleus with mass number A is approximately 8 MeV. If this nucleus splits into two equal fragments, approximately how much energy is released?",
            options: [
                "0 MeV",
                "4A MeV",
                "A MeV",
                "8A MeV"
            ],
            correct: 2, // C
            marks: 4
        }
    ]
};

// [REST OF THE JAVASCRIPT CODE - EXAM ENGINE EXACTLY AS IN 2023]
let currentSection = 'Biology';
let currentQuestionIndex = 0;
let answers = {};
let markedForReview = {};
let visited = {};
let timeLeft = 10800;
let timerInterval = null;
let userName = 'Student';
let violations = 0;

document.addEventListener('DOMContentLoaded', function() {
    setupEventListeners();
});

function setupEventListeners() {
    const beginBtn = document.getElementById('beginTestBtn');
    if (beginBtn) beginBtn.addEventListener('click', startExam);

    document.querySelectorAll('.section-tab').forEach(tab => {
        tab.addEventListener('click', function() {
            const section = this.getAttribute('data-section');
            switchSection(section);
        });
    });

    const markBtn = document.getElementById('markReviewBtn');
    const clearBtn = document.getElementById('clearBtn');
    const saveBtn = document.getElementById('saveNextBtn');
    const submitBtn = document.getElementById('submitExamBtn');

    if (markBtn) markBtn.addEventListener('click', toggleMarkForReview);
    if (clearBtn) clearBtn.addEventListener('click', clearResponse);
    if (saveBtn) saveBtn.addEventListener('click', saveAndNext);
    if (submitBtn) submitBtn.addEventListener('click', submitExam);

    const agreeTerms = document.getElementById('agreeTerms');
    const beginTestBtn = document.getElementById('beginTestBtn');
    
    if (agreeTerms && beginTestBtn) {
        beginTestBtn.disabled = !agreeTerms.checked;
        agreeTerms.addEventListener('change', function() {
            beginTestBtn.disabled = !this.checked;
        });
    }

    const nameInput = document.getElementById('candidateName');
    if (nameInput) {
        nameInput.addEventListener('change', function() {
            userName = this.value || 'Student';
        });
    }
}

function startExam() {
    const instructionPage = document.getElementById('instructionPage');
    const examInterface = document.getElementById('examInterface');
    
    if (instructionPage) instructionPage.style.display = 'none';
    if (examInterface) examInterface.style.display = 'block';

    const userNameEl = document.getElementById('userName');
    if (userNameEl) userNameEl.textContent = userName;

    loadQuestion();
    updatePalette();
    startTimer();
    updateSectionCounts();
}

function startTimer() {
    updateTimerDisplay();
    timerInterval = setInterval(() => {
        timeLeft--;
        updateTimerDisplay();
        if (timeLeft <= 0) autoSubmitExam();
    }, 1000);
}

function updateTimerDisplay() {
    const hours = Math.floor(timeLeft / 3600);
    const minutes = Math.floor((timeLeft % 3600) / 60);
    const seconds = timeLeft % 60;
    
    const display = `Time Left : ${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
    
    const timerEl = document.getElementById('timerDisplay');
    if (timerEl) timerEl.textContent = display;
}

function loadQuestion() {
    const questions = questionBank[currentSection];
    const question = questions[currentQuestionIndex];
    const questionKey = `${currentSection}-${currentQuestionIndex}`;

    visited[questionKey] = true;

    const qNumEl = document.getElementById('questionNumberDisplay');
    if (qNumEl) qNumEl.textContent = `Question No. ${currentQuestionIndex + 1}`;

    const qTextEl = document.getElementById('questionContent');
    if (qTextEl) qTextEl.innerHTML = `<p class="question-text">${question.text}</p>`;

    const optionsContainer = document.getElementById('optionsContainer');
    if (optionsContainer) {
        optionsContainer.innerHTML = '';
        
        question.options.forEach((option, index) => {
            const optionDiv = document.createElement('div');
            optionDiv.className = 'option-item';
            if (answers[questionKey] === index) optionDiv.classList.add('selected');
            
            optionDiv.innerHTML = `
                <input type="radio" name="question" value="${index}" ${answers[questionKey] === index ? 'checked' : ''}>
                <span class="option-text"><strong>(${String.fromCharCode(97 + index)})</strong> ${option}</span>
            `;
            
            optionDiv.addEventListener('click', function() { selectAnswer(index); });
            optionsContainer.appendChild(optionDiv);
        });
    }

    const sectionTitleEl = document.getElementById('sectionTitle');
    if (sectionTitleEl) sectionTitleEl.textContent = currentSection;

    updatePalette();
}

function selectAnswer(optionIndex) {
    const questionKey = `${currentSection}-${currentQuestionIndex}`;
    answers[questionKey] = optionIndex;
    
    document.querySelectorAll('.option-item').forEach((item, index) => {
        if (index === optionIndex) {
            item.classList.add('selected');
            item.querySelector('input').checked = true;
        } else {
            item.classList.remove('selected');
            item.querySelector('input').checked = false;
        }
    });
    
    updatePalette();
    updateSectionCounts();
}

function switchSection(section) {
    currentSection = section;
    currentQuestionIndex = 0;
    
    document.querySelectorAll('.section-tab').forEach(tab => {
        if (tab.getAttribute('data-section') === section) tab.classList.add('active');
        else tab.classList.remove('active');
    });
    
    loadQuestion();
}

function toggleMarkForReview() {
    const questionKey = `${currentSection}-${currentQuestionIndex}`;
    markedForReview[questionKey] = !markedForReview[questionKey];
    updatePalette();
    saveAndNext();
}

function clearResponse() {
    const questionKey = `${currentSection}-${currentQuestionIndex}`;
    delete answers[questionKey];
    loadQuestion();
    updateSectionCounts();
}

function saveAndNext() {
    const questions = questionBank[currentSection];
    if (currentQuestionIndex < questions.length - 1) {
        currentQuestionIndex++;
        loadQuestion();
    }
}

function updatePalette() {
    const paletteEl = document.getElementById('questionPalette');
    if (!paletteEl) return;
    
    paletteEl.innerHTML = '';
    const questions = questionBank[currentSection];
    
    questions.forEach((_, index) => {
        const btn = document.createElement('button');
        btn.className = 'palette-btn';
        btn.textContent = index + 1;
        
        const questionKey = `${currentSection}-${index}`;
        
        if (index === currentQuestionIndex) btn.classList.add('current');
        
        if (markedForReview[questionKey]) btn.classList.add('marked');
        else if (answers[questionKey] !== undefined) btn.classList.add('answered');
        else if (visited[questionKey]) btn.classList.add('not-answered');
        else btn.classList.add('not-visited');
        
        btn.addEventListener('click', () => {
            currentQuestionIndex = index;
            loadQuestion();
        });
        
        paletteEl.appendChild(btn);
    });
}

function updateSectionCounts() {
    const sections = ['Biology', 'Chemistry', 'Mathematics', 'Physics'];
    
    sections.forEach(section => {
        let answered = 0;
        const questions = questionBank[section];
        
        questions.forEach((_, index) => {
            const key = `${section}-${index}`;
            if (answers[key] !== undefined) answered++;
        });
        
        const countEl = document.getElementById(`${section.toLowerCase()}Count`);
        if (countEl) countEl.textContent = answered;
    });
}

function submitExam() {
    if (confirm('Are you sure you want to submit the exam?')) autoSubmitExam();
}

function autoSubmitExam() {
    if (timerInterval) {
        clearInterval(timerInterval);
        timerInterval = null;
    }

    const results = calculateScore();
    showResults(results);
}

function calculateScore() {
    let totalScore = 0;
    let maxScore = 0;
    let totalAttempted = 0;
    let totalCorrect = 0;
    let totalQuestions = 0;
    let sectionBreakdown = {};

    Object.keys(questionBank).forEach(section => {
        const qArr = questionBank[section];
        const marksPerQuestion = 4;
        
        sectionBreakdown[section] = {
            obtained: 0,
            max: qArr.length * marksPerQuestion,
            attempted: 0,
            correctCount: 0,
            totalQuestions: qArr.length
        };

        qArr.forEach((q, idx) => {
            totalQuestions++;
            maxScore += marksPerQuestion;
            const key = `${section}-${idx}`;
            const ans = answers[key];
            
            if (ans !== undefined && ans !== null) {
                totalAttempted++;
                sectionBreakdown[section].attempted++;
                
                if (ans === q.correct) {
                    totalCorrect++;
                    totalScore += marksPerQuestion;
                    sectionBreakdown[section].obtained += marksPerQuestion;
                    sectionBreakdown[section].correctCount++;
                } else {
                    totalScore -= 1;
                    sectionBreakdown[section].obtained -= 1;
                }
            }
        });
    });

    return {
        totalScore,
        maxScore,
        totalAttempted,
        totalCorrect,
        totalQuestions,
        sectionBreakdown
    };
}

function showResults(results) {
    const examInterface = document.getElementById('examInterface');
    if (!examInterface) {
        alert(`Exam Submitted!\n\nTotal Score: ${results.totalScore}/${results.maxScore}\nAttempted: ${results.totalAttempted}/${results.totalQuestions}\nCorrect: ${results.totalCorrect}`);
        return;
    }

    examInterface.innerHTML = `
        <div style="max-width: 900px; margin: 50px auto; padding: 30px; background: white; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <h1 style="color: #2563eb; text-align: center; margin-bottom: 30px;">Exam Results</h1>
            
            <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
                <h2 style="margin: 0 0 20px 0; color: #334155;">Overall Performance</h2>
                <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px;">
                    <div style="background: white; padding: 15px; border-radius: 6px;">
                        <div style="font-size: 14px; color: #64748b; margin-bottom: 5px;">Total Score</div>
                        <div style="font-size: 28px; font-weight: bold; color: ${results.totalScore >= 0 ? '#10b981' : '#ef4444'};">${results.totalScore} / ${results.maxScore}</div>
                    </div>
                    <div style="background: white; padding: 15px; border-radius: 6px;">
                        <div style="font-size: 14px; color: #64748b; margin-bottom: 5px;">Attempted</div>
                        <div style="font-size: 28px; font-weight: bold; color: #2563eb;">${results.totalAttempted} / ${results.totalQuestions}</div>
                    </div>
                    <div style="background: white; padding: 15px; border-radius: 6px;">
                        <div style="font-size: 14px; color: #64748b; margin-bottom: 5px;">Correct Answers</div>
                        <div style="font-size: 28px; font-weight: bold; color: #10b981;">${results.totalCorrect}</div>
                    </div>
                </div>
            </div>

            <h2 style="color: #334155; margin-bottom: 20px;">Section-wise Breakdown</h2>
            <table style="width: 100%; border-collapse: collapse; background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
                <thead>
                    <tr style="background: #f1f5f9;">
                        <th style="text-align: left; padding: 15px; border-bottom: 2px solid #e2e8f0; color: #475569;">Section</th>
                        <th style="text-align: right; padding: 15px; border-bottom: 2px solid #e2e8f0; color: #475569;">Score</th>
                        <th style="text-align: right; padding: 15px; border-bottom: 2px solid #e2e8f0; color: #475569;">Max Score</th>
                        <th style="text-align: right; padding: 15px; border-bottom: 2px solid #e2e8f0; color: #475569;">Attempted</th>
                        <th style="text-align: right; padding: 15px; border-bottom: 2px solid #e2e8f0; color: #475569;">Correct</th>
                    </tr>
                </thead>
                <tbody>
                    ${Object.keys(results.sectionBreakdown).map(section => {
                        const s = results.sectionBreakdown[section];
                        return `
                            <tr>
                                <td style="padding: 15px; border-bottom: 1px solid #e2e8f0; font-weight: 500;">${section}</td>
                                <td style="padding: 15px; text-align: right; border-bottom: 1px solid #e2e8f0; color: ${s.obtained >= 0 ? '#10b981' : '#ef4444'}; font-weight: 500;">${s.obtained}</td>
                                <td style="padding: 15px; text-align: right; border-bottom: 1px solid #e2e8f0;">${s.max}</td>
                                <td style="padding: 15px; text-align: right; border-bottom: 1px solid #e2e8f0;">${s.attempted} / ${s.totalQuestions}</td>
                                <td style="padding: 15px; text-align: right; border-bottom: 1px solid #e2e8f0;">${s.correctCount}</td>
                            </tr>
                        `;
                    }).join('')}
                </tbody>
            </table>

            <div style="text-align: center; margin-top: 40px;">
                <button onclick="location.reload()" style="background: #2563eb; color: white; padding: 12px 30px; border: none; border-radius: 6px; font-size: 16px; font-weight: 500; cursor: pointer; box-shadow: 0 2px 4px rgba(37,99,235,0.2);">
                    Start New Exam
                </button>
            </div>
        </div>
    `;
}

console.log('Exam 2022 initialized successfully!');